import pandas as pd
from .base_strategy import BaseStrategy

class BuyAndHoldStrategy(BaseStrategy):
    """
    Buy and Hold Trading Strategy.
    Generates a single buy signal on the first day of the data.
    Holds the position until the end of the backtest.
    """

    def __init__(self):
        """
        Initializes the BuyAndHoldStrategy.
        """
        self._name = "Buy and Hold"

    def generate_signals(self, data: pd.DataFrame) -> pd.Series:
        """
        Generates a single buy signal on the first day.
        """
        if data.empty:
            return pd.Series(0, index=data.index)

        signals = pd.Series(0, index=data.index)

        # Generate a buy signal on the very first day
        signals.iloc[0] = 1

        # No sell signals are generated by this strategy;
        # the backtester will automatically close positions at the end.

        return signals

    @property
    def name(self) -> str:
        """
        Returns the name of the strategy.
        """
        return self._name

    def get_params(self) -> dict:
        """
        Returns the parameters of the strategy.
        Buy and Hold has no configurable parameters.
        """
        return {}
